// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/vladislav-koval/url-shortener/internal/analytics/stats/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountByShortCodes mocks base method.
func (m *MockRepository) CountByShortCodes(ctx context.Context, shortCodes []string) ([]domain.LinkClickCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByShortCodes", ctx, shortCodes)
	ret0, _ := ret[0].([]domain.LinkClickCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByShortCodes indicates an expected call of CountByShortCodes.
func (mr *MockRepositoryMockRecorder) CountByShortCodes(ctx, shortCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByShortCodes", reflect.TypeOf((*MockRepository)(nil).CountByShortCodes), ctx, shortCodes)
}
