services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - shortener
      - frontend
    restart: always

  analytics:
    build:
      context: .
      dockerfile: ./cmd/analytics/Dockerfile
    container_name: analytics
    environment:
      - GRPC_ADDR=${GRPC_ADDR}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_CONSUMER_BATCH_SIZE=${KAFKA_CONSUMER_BATCH_SIZE}
      - KAFKA_CONSUMER_BATCH_TIMEOUT=${KAFKA_CONSUMER_BATCH_TIMEOUT}
      - KAFKA_CONSUMER_GOROUTINES_COUNT=${KAFKA_CONSUMER_GOROUTINES_COUNT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/out/logs
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
    volumes:
      - ./out/logs/analytics:/app/out/logs
    restart: always

  shortener:
    build:
      context: .
      dockerfile: ./cmd/urlshortener/Dockerfile
    container_name: shortener
    environment:
      - GRPC_ADDR=${GRPC_ADDR}
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - SHORTENER_CACHE_TTL=${SHORTENER_CACHE_TTL}
      - GRPC_CLIENT_ADDR=analytics${GRPC_ADDR}
      - GRPC_CLIENT_MAX_RETRIES=${GRPC_CLIENT_MAX_RETRIES}
      - GRPC_CLIENT_PER_TIMEOUT=${GRPC_CLIENT_PER_TIMEOUT}
      - GEO_FILE_PATH=${GEO_FILE_PATH}
      - GEO_REQUIRED=${GEO_REQUIRED}
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_PRODUCER_BATCH_SIZE=${KAFKA_PRODUCER_BATCH_SIZE}
      - KAFKA_PRODUCER_QUEUE_SIZE=${KAFKA_PRODUCER_QUEUE_SIZE}
      - KAFKA_PRODUCER_FLUSH_INTERVAL=${KAFKA_PRODUCER_FLUSH_INTERVAL}
      - KAFKA_PRODUCER_WRITE_TIMEOUT=${KAFKA_PRODUCER_WRITE_TIMEOUT}
      - AUTHORIZATION_COOKIE_SECURE=${AUTHORIZATION_COOKIE_SECURE}
      - AUTH_SUCCESS_REDIRECT_URL=${AUTH_SUCCESS_REDIRECT_URL}
      - AUTH_SESSION_TTL=${AUTH_SESSION_TTL}
      - GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}
      - GOOGLE_AUTH_CLIENT_SECRET=${GOOGLE_AUTH_CLIENT_SECRET}
      - GOOGLE_AUTH_CALLBACK_URL=${GOOGLE_AUTH_CALLBACK_URL}
      - HTTP_ADDR=${HTTP_ADDR}
      - HTTP_ALLOWED_ORIGINS=${HTTP_ALLOWED_ORIGINS}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=/app/out/logs
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
    volumes:
      - ./out/logs/shortener:/app/out/logs
    restart: always

  frontend:
    build:
      context: ../url-shortener-front
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
    container_name: frontend
    depends_on:
      - shortener
    restart: always

  postgres-migrate:
    profiles:
      - tools

    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations

  postgres:
    image: postgres:18.4-bookworm
    container_name: url-shortener-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

  redis:
    image: redis:8.8.0-alpine
    container_name: url-shortener-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.2.1
    container_name: url-shortener-redpanda
    command:
      - redpanda
      - start
      - --mode dev-container
      - --smp 1
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://${KAFKA_ADVERTISED_HOST}:19092
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda:33145
    ports:
      - "127.0.0.1:19092:19092"
    volumes:
      - kafkadata:/var/lib/redpanda/data
    restart: always
    mem_limit: 512m

  port-forwarder:
    profiles:
      - tools

    image: alpine/socat:1.8.0.3
    container_name: url-shortener-pg-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:postgres:5432
    ports:
      - "127.0.0.1:5432:5432"


volumes:
  pgdata:
  kafkadata:
  caddy_data:
  caddy_config: