services:
  postgres-migrate:
    profiles:
      - tools

    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations

  postgres:
    image: postgres:18.4-bookworm
    container_name: url-shortener-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

  redis:
    image: redis:8.8.0-alpine
    container_name: url-shortener-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    restart: always

  port-forwarder:
    profiles:
      - tools

    image: alpine/socat:1.8.0.3
    container_name: url-shortener-pg-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:postgres:5432
    ports:
      - "127.0.0.1:5432:5432"


volumes:
  pgdata: