// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/shortener/urls/repository/cached/repository.go
//
// Generated by this command:
//
//	mockgen -source=./internal/shortener/urls/repository/cached/repository.go -destination=./internal/shortener/urls/repository/cached/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/vladislav-koval/url-shortener/internal/shortener/urls/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUnderlyingRepository is a mock of UnderlyingRepository interface.
type MockUnderlyingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUnderlyingRepositoryMockRecorder
	isgomock struct{}
}

// MockUnderlyingRepositoryMockRecorder is the mock recorder for MockUnderlyingRepository.
type MockUnderlyingRepositoryMockRecorder struct {
	mock *MockUnderlyingRepository
}

// NewMockUnderlyingRepository creates a new mock instance.
func NewMockUnderlyingRepository(ctrl *gomock.Controller) *MockUnderlyingRepository {
	mock := &MockUnderlyingRepository{ctrl: ctrl}
	mock.recorder = &MockUnderlyingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnderlyingRepository) EXPECT() *MockUnderlyingRepositoryMockRecorder {
	return m.recorder
}

// CreateShortLink mocks base method.
func (m *MockUnderlyingRepository) CreateShortLink(ctx context.Context, shortCode, originalURL string, userID *uuid.UUID) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLink", ctx, shortCode, originalURL, userID)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortLink indicates an expected call of CreateShortLink.
func (mr *MockUnderlyingRepositoryMockRecorder) CreateShortLink(ctx, shortCode, originalURL, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLink", reflect.TypeOf((*MockUnderlyingRepository)(nil).CreateShortLink), ctx, shortCode, originalURL, userID)
}

// GetByShortCode mocks base method.
func (m *MockUnderlyingRepository) GetByShortCode(ctx context.Context, code string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShortCode", ctx, code)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShortCode indicates an expected call of GetByShortCode.
func (mr *MockUnderlyingRepositoryMockRecorder) GetByShortCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShortCode", reflect.TypeOf((*MockUnderlyingRepository)(nil).GetByShortCode), ctx, code)
}
