// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pagination "github.com/vladislav-koval/url-shortener/internal/platform/pagination"
	domain "github.com/vladislav-koval/url-shortener/internal/shortener/stats/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetLinksByUserID mocks base method.
func (m *MockRepository) GetLinksByUserID(ctx context.Context, userID uuid.UUID, p pagination.Pagination) ([]domain.Link, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinksByUserID", ctx, userID, p)
	ret0, _ := ret[0].([]domain.Link)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLinksByUserID indicates an expected call of GetLinksByUserID.
func (mr *MockRepositoryMockRecorder) GetLinksByUserID(ctx, userID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinksByUserID", reflect.TypeOf((*MockRepository)(nil).GetLinksByUserID), ctx, userID, p)
}

// MockGRPCClient is a mock of GRPCClient interface.
type MockGRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCClientMockRecorder
	isgomock struct{}
}

// MockGRPCClientMockRecorder is the mock recorder for MockGRPCClient.
type MockGRPCClientMockRecorder struct {
	mock *MockGRPCClient
}

// NewMockGRPCClient creates a new mock instance.
func NewMockGRPCClient(ctrl *gomock.Controller) *MockGRPCClient {
	mock := &MockGRPCClient{ctrl: ctrl}
	mock.recorder = &MockGRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCClient) EXPECT() *MockGRPCClientMockRecorder {
	return m.recorder
}

// GetClickCounts mocks base method.
func (m *MockGRPCClient) GetClickCounts(ctx context.Context, shortCodes []string) ([]domain.LinkClickCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClickCounts", ctx, shortCodes)
	ret0, _ := ret[0].([]domain.LinkClickCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClickCounts indicates an expected call of GetClickCounts.
func (mr *MockGRPCClientMockRecorder) GetClickCounts(ctx, shortCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClickCounts", reflect.TypeOf((*MockGRPCClient)(nil).GetClickCounts), ctx, shortCodes)
}
