// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vladislav-koval/url-shortener/api/gen/analytics/v1 (interfaces: AnalyticsServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_analytics_client.go -package=mocks github.com/vladislav-koval/url-shortener/api/gen/analytics/v1 AnalyticsServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	analyticsv1 "github.com/vladislav-koval/url-shortener/api/gen/analytics/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAnalyticsServiceClient is a mock of AnalyticsServiceClient interface.
type MockAnalyticsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsServiceClientMockRecorder
	isgomock struct{}
}

// MockAnalyticsServiceClientMockRecorder is the mock recorder for MockAnalyticsServiceClient.
type MockAnalyticsServiceClientMockRecorder struct {
	mock *MockAnalyticsServiceClient
}

// NewMockAnalyticsServiceClient creates a new mock instance.
func NewMockAnalyticsServiceClient(ctrl *gomock.Controller) *MockAnalyticsServiceClient {
	mock := &MockAnalyticsServiceClient{ctrl: ctrl}
	mock.recorder = &MockAnalyticsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsServiceClient) EXPECT() *MockAnalyticsServiceClientMockRecorder {
	return m.recorder
}

// GetLinkClickCounts mocks base method.
func (m *MockAnalyticsServiceClient) GetLinkClickCounts(ctx context.Context, in *analyticsv1.GetLinkClickCountsRequest, opts ...grpc.CallOption) (*analyticsv1.GetLinkClickCountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLinkClickCounts", varargs...)
	ret0, _ := ret[0].(*analyticsv1.GetLinkClickCountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkClickCounts indicates an expected call of GetLinkClickCounts.
func (mr *MockAnalyticsServiceClientMockRecorder) GetLinkClickCounts(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkClickCounts", reflect.TypeOf((*MockAnalyticsServiceClient)(nil).GetLinkClickCounts), varargs...)
}
