// Code generated by MockGen. DO NOT EDIT.
// Source: ./pool.go
//
// Generated by this command:
//
//	mockgen -source=./pool.go -destination=mocks/mock_pool.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/vladislav-koval/url-shortener/internal/platform/repository/redis"
	gomock "go.uber.org/mock/gomock"
)

// MockPool is a mock of Pool interface.
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMockRecorder
	isgomock struct{}
}

// MockPoolMockRecorder is the mock recorder for MockPool.
type MockPoolMockRecorder struct {
	mock *MockPool
}

// NewMockPool creates a new mock instance.
func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &MockPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPool) EXPECT() *MockPoolMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPool) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPoolMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPool)(nil).Close))
}

// Del mocks base method.
func (m *MockPool) Del(ctx context.Context, keys ...string) cache.IntCmd {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Del", varargs...)
	ret0, _ := ret[0].(cache.IntCmd)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockPoolMockRecorder) Del(ctx any, keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockPool)(nil).Del), varargs...)
}

// Get mocks base method.
func (m *MockPool) Get(ctx context.Context, key string) cache.StringCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(cache.StringCmd)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockPoolMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPool)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockPool) Set(ctx context.Context, key string, value any, expiration time.Duration) cache.StatusCmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(cache.StatusCmd)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPoolMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPool)(nil).Set), ctx, key, value, expiration)
}

// MockStringCmd is a mock of StringCmd interface.
type MockStringCmd struct {
	ctrl     *gomock.Controller
	recorder *MockStringCmdMockRecorder
	isgomock struct{}
}

// MockStringCmdMockRecorder is the mock recorder for MockStringCmd.
type MockStringCmdMockRecorder struct {
	mock *MockStringCmd
}

// NewMockStringCmd creates a new mock instance.
func NewMockStringCmd(ctrl *gomock.Controller) *MockStringCmd {
	mock := &MockStringCmd{ctrl: ctrl}
	mock.recorder = &MockStringCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStringCmd) EXPECT() *MockStringCmdMockRecorder {
	return m.recorder
}

// Result mocks base method.
func (m *MockStringCmd) Result() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Result")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Result indicates an expected call of Result.
func (mr *MockStringCmdMockRecorder) Result() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Result", reflect.TypeOf((*MockStringCmd)(nil).Result))
}

// MockStatusCmd is a mock of StatusCmd interface.
type MockStatusCmd struct {
	ctrl     *gomock.Controller
	recorder *MockStatusCmdMockRecorder
	isgomock struct{}
}

// MockStatusCmdMockRecorder is the mock recorder for MockStatusCmd.
type MockStatusCmdMockRecorder struct {
	mock *MockStatusCmd
}

// NewMockStatusCmd creates a new mock instance.
func NewMockStatusCmd(ctrl *gomock.Controller) *MockStatusCmd {
	mock := &MockStatusCmd{ctrl: ctrl}
	mock.recorder = &MockStatusCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusCmd) EXPECT() *MockStatusCmdMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockStatusCmd) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockStatusCmdMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockStatusCmd)(nil).Err))
}

// MockIntCmd is a mock of IntCmd interface.
type MockIntCmd struct {
	ctrl     *gomock.Controller
	recorder *MockIntCmdMockRecorder
	isgomock struct{}
}

// MockIntCmdMockRecorder is the mock recorder for MockIntCmd.
type MockIntCmdMockRecorder struct {
	mock *MockIntCmd
}

// NewMockIntCmd creates a new mock instance.
func NewMockIntCmd(ctrl *gomock.Controller) *MockIntCmd {
	mock := &MockIntCmd{ctrl: ctrl}
	mock.recorder = &MockIntCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntCmd) EXPECT() *MockIntCmdMockRecorder {
	return m.recorder
}

// Err mocks base method.
func (m *MockIntCmd) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockIntCmdMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockIntCmd)(nil).Err))
}
