// Code generated by MockGen. DO NOT EDIT.
// Source: ./service.go
//
// Generated by this command:
//
//	mockgen -source=./service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	events "github.com/vladislav-koval/url-shortener/internal/platform/messaging/events"
	domain "github.com/vladislav-koval/url-shortener/internal/shortener/urls/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateShortLink mocks base method.
func (m *MockRepository) CreateShortLink(ctx context.Context, shortCode, originalURL string, userID *uuid.UUID) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLink", ctx, shortCode, originalURL, userID)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortLink indicates an expected call of CreateShortLink.
func (mr *MockRepositoryMockRecorder) CreateShortLink(ctx, shortCode, originalURL, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLink", reflect.TypeOf((*MockRepository)(nil).CreateShortLink), ctx, shortCode, originalURL, userID)
}

// GetByShortCode mocks base method.
func (m *MockRepository) GetByShortCode(ctx context.Context, code string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShortCode", ctx, code)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShortCode indicates an expected call of GetByShortCode.
func (mr *MockRepositoryMockRecorder) GetByShortCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShortCode", reflect.TypeOf((*MockRepository)(nil).GetByShortCode), ctx, code)
}

// MockClickRecorder is a mock of ClickRecorder interface.
type MockClickRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockClickRecorderMockRecorder
	isgomock struct{}
}

// MockClickRecorderMockRecorder is the mock recorder for MockClickRecorder.
type MockClickRecorderMockRecorder struct {
	mock *MockClickRecorder
}

// NewMockClickRecorder creates a new mock instance.
func NewMockClickRecorder(ctrl *gomock.Controller) *MockClickRecorder {
	mock := &MockClickRecorder{ctrl: ctrl}
	mock.recorder = &MockClickRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickRecorder) EXPECT() *MockClickRecorderMockRecorder {
	return m.recorder
}

// RecordClick mocks base method.
func (m *MockClickRecorder) RecordClick(clickEvent events.ClickEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordClick", clickEvent)
}

// RecordClick indicates an expected call of RecordClick.
func (mr *MockClickRecorderMockRecorder) RecordClick(clickEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClick", reflect.TypeOf((*MockClickRecorder)(nil).RecordClick), clickEvent)
}
