// Code generated by MockGen. DO NOT EDIT.
// Source: ./handler.go
//
// Generated by this command:
//
//	mockgen -source=./handler.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/vladislav-koval/url-shortener/internal/analytics/stats/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetLinkClickCount mocks base method.
func (m *MockService) GetLinkClickCount(ctx context.Context, shortCodes []string) ([]domain.LinkClickCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkClickCount", ctx, shortCodes)
	ret0, _ := ret[0].([]domain.LinkClickCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkClickCount indicates an expected call of GetLinkClickCount.
func (mr *MockServiceMockRecorder) GetLinkClickCount(ctx, shortCodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkClickCount", reflect.TypeOf((*MockService)(nil).GetLinkClickCount), ctx, shortCodes)
}
